name: PHP-hexlet

on:
  push:
    branches:
      - master

jobs:
    build:
            runs-on: ununtu-latest

            steps:
                - uses: actions/checkout@v2
                - name: Hexlet project check
                  uses: hexlet/project-action@release
                  with:
                      hexlet-id: ${{ secrets.HEXLET_ID }}
                - name: lint
                  run : make lint     
                - name: test
                  run : make test
